# Generated by Django 4.1 on 2022-08-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal_colors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("thumbnail", models.TextField()),
                (
                    "personal_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_colors.personalcolor",
                    ),
                ),
            ],
            options={"db_table": "posts",},
        ),
    ]
