# Generated by Django 4.1 on 2022-08-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="personal_color", new_name="type",
        ),
    ]
